# Generated by Django 5.1.1 on 2024-10-15 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.CharField(max_length=200)),
                ('precio', models.FloatField()),
                ('disponibilidad', models.IntegerField(max_length=200)),
            ],
        ),
    ]
