# Generated by Django 5.1.1 on 2024-10-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vams', '0002_productos_categoria_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=None)),
                ('precio_unitario', models.FloatField(default=None)),
                ('total', models.FloatField(default=None)),
            ],
        ),
    ]
